sudo: required
services:
  - docker

before_install:
  - docker build -t tetherdev/dockerhub -f Dockerfile.dev .

script:
  - docker run tetherdev/dockerhub npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockerhub"
  env: "Dockerhub-env"
  bucker_name: elasticbeanstalk-us-west-2-075083687404
  bucket_path: "dockerhub"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  